apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
nameSuffix: -app2
namespace: app2

patches:
  - target:
      kind: Ingress
      name: whoami
    patch: |
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /app2
